angular
	.module('parkSearch')
	.controller('parkSearchController', function($scope, parksFactory) {

		// Will be generated by the database
		$scope.parks;

			$scope.showBrowse = true;
			$scope.showSearch = false;
			$scope.showLogin = false;

		parksFactory.getParks().then(function(data) {
			$scope.parks = data.data;
		}, function(error) {
			console.log(error);
		});

		// switch between tabs
		$scope.switchTab = function (tab) {

			$scope.showBrowse = false;
			$scope.showSearch = false;
			$scope.showLogin = false;
			if (tab == 'browse')
				$scope.showBrowse = true;
			else if (tab == 'search')
				$scope.showSearch = true;
			else if (tab == 'login')
				$scope.showLogin = true;
			
		}
	});